# Generated by Django 4.2.5 on 2023-09-13 21:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('unit', models.CharField(help_text='The full name of the unit of measurement', max_length=32)),
                ('symbol', models.CharField(help_text='The symbol for the unit of measurement', max_length=16)),
                ('description', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('measurement', models.FloatField(help_text='The value of the measurement taken', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('notes', models.CharField(max_length=1024)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measurements.measurementtype')),
            ],
        ),
    ]
