# Generated by Django 4.2.5 on 2023-09-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='added',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='updated',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='measurementtype',
            name='description',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='measurementtype',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
