apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fitness-tracker
resources:
- ../../base/

commonLabels:
  app: fitness-tracker
  env: prod

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: fitness-tracker-config
  envs:
  - data_configmap.properties

secretGenerator:
- name: fitness-tracker-secrets
  envs:
  - data_secret.properties

patches:
- path: patch_app.yaml
  target:
    kind: Deployment
    name: fitness-tracker
- path: patch_ingress.yaml
  target:
    kind: Ingress
    name: fitness-tracker-ingress
- path: patch_proxy.yaml
  target:
    kind: Deployment
    name: fitness-tracker-proxy
