# Generated by Django 4.2.5 on 2023-09-20 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionexercise',
            name='reps',
            field=models.PositiveIntegerField(blank=True, help_text='Number of repetitions per set', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight used in kg, negative implies weighted assistance', null=True, validators=[django.core.validators.MinValueValidator(-1000.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
    ]
