# Generated by Django 4.2.5 on 2023-09-13 21:11

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='distance',
            field=models.PositiveIntegerField(blank=True, help_text='Distance covered in metres', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Time taken in seconds', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(604800)]),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='reps',
            field=models.PositiveIntegerField(blank=True, help_text='Number of repetitions per set', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, help_text='Number of sets completed', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight used in kg', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
    ]
