# Generated by Django 4.2.5 on 2023-11-11 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_sessionexercise_reps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexercise',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Calories (kcal) burned', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
