# Generated by Django 4.2.5 on 2023-09-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_session_date_alter_sessionexercise_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='description',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
