# Generated by Django 4.2.5 on 2023-11-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_fooditem_unit_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='incomplete_data',
            field=models.BooleanField(default=False, help_text='The data for this journal is not complete'),
        ),
    ]
