name: Build and push container images

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
        - context: ./app/
          image: ${{ github.repository }}
        - context: ./proxy/
          image: ${{ github.repository }}-proxy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (labels, tags) for container
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ matrix.image }}
        tags: |
          type=semver,pattern={{version}}

    - name: Build and push app container image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

